<?xml version="1.0"?>
<!DOCTYPE blackdeck [
		<!ELEMENT blackdeck (cardData)*>
		<!ATTLIST blackdeck
				name CDATA #REQUIRED>
		<!ELEMENT cardData (text|draw|pick)*>
		<!ELEMENT text (#PCDATA)>
		<!ELEMENT draw (#PCDATA)>
		<!ELEMENT pick (#PCDATA)>
		]>
<blackdeck name="Main deck">
	<cardData>
		<text>______ + ______ = ______.</text>
		<draw>2</draw>
		<pick>3</pick>
	</cardData>
	<cardData>
		<text>______ is a slippery slope that leads to ______.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>______: good to the last drop.</text>
		
	</cardData>
	<cardData>
		<text>______: kid-tested, mother-approved.</text>
		
	</cardData>
	<cardData>
		<text>______. Betcha can't have just one!</text>
		
	</cardData>
	<cardData>
		<text>______. High five, bro.</text>
		
	</cardData>
	<cardData>
		<text>______. It's a trap!</text>
		
	</cardData>
	<cardData>
		<text>A romantic, candlelit dinner would be incomplete without ______.</text>
		
	</cardData>
	<cardData>
		<text>After the earthquake, Sean Penn brought ______ to the people of Haiti.</text>
		
	</cardData>
	<cardData>
		<text>Alternative medicine is now embracing the curative powers of ______.</text>
		
	</cardData>
	<cardData>
		<text>And the Academy Award for ______ goes to ______.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>But before I kill you, Mr. Bond, I must show you ______.</text>
		
	</cardData>
	<cardData>
		<text>Coming to Broadway this season, ______: The Musical.</text>
		
	</cardData>
	<cardData>
		<text>Daddy, why is mommy crying?</text>
		
	</cardData>
	<cardData>
		<text>Dear Abby,
  I'm having some trouble with ______ and would like your advice.</text>
	</cardData>
	<cardData>
		<text>During sex, I like to think about ______.</text>
		
	</cardData>
	<cardData>
		<text>For my next trick, I will pull ______ out of ______.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>Here is the church Here is the steeple Open the doors And there is ______.</text>
		
	</cardData>
	<cardData>
		<text>How am I maintaining my relationship status?</text>
		
	</cardData>
	<cardData>
		<text>How did I lose my virginity?</text>
		
	</cardData>
	<cardData>
		<text>I drink to forget ______.</text>
		
	</cardData>
	<cardData>
		<text>I got 99 problems but ______ ain't one.</text>
		
	</cardData>
	<cardData>
		<text>I never truly understood ______ until I encountered ______.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>I'm sorry, Professor, but I couldn't complete my homework because of ______.</text>
		
	</cardData>
	<cardData>
		<text>In a world ravaged by ______, our only solace is ______.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>In L.A. County Jail, word is you can trade 200 cigarettes for ______.</text>
		
	</cardData>
	<cardData>
		<text>In M. Night Shyamalan's new movie, Bruce Willis discovers that ______ had really been ______ all along.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>In the new Disney Channel Original Movie, Hannah Montana struggles with ______ for the first time.</text>
		
	</cardData>
	<cardData>
		<text>Instead of coal, Santa now gives the bad children ______.</text>
		
	</cardData>
	<cardData>
		<text>It’s a pity that kids these days are all getting involved with ______.</text>
		
	</cardData>
	<cardData>
		<text>Life for American Indians was forever changed when the White Man introduced them to ______.</text>
		
	</cardData>
	<cardData>
		<text>Lifetime® presents "______: the Story of ______."</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>Make a haiku.</text>
		<draw>2</draw>
		<pick>3</pick>
	</cardData>
	<cardData>
		<text>Maybe she's born with it. Maybe it's ______.</text>
		
	</cardData>
	<cardData>
		<text>MTV's new reality show features eight washed-up celebrities living with ______.</text>
		
	</cardData>
	<cardData>
		<text>Next from J.K. Rowling: Harry Potter and the Chamber of ______.</text>
		
	</cardData>
	<cardData>
		<text>Next on ESPN2: The World Series of ______.</text>
		
	</cardData>
	<cardData>
		<text>Step 1: ______. Step 2: ______. Step 3: Profit.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>That's right, I killed ______. How, you ask? ______.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>The class field trip was completely ruined by ______.</text>
		
	</cardData>
	<cardData>
		<text>This is the way the world ends\nThis is the way the world ends\nNot with a bang but with ______.</text>
		
	</cardData>
	<cardData>
		<text>TSA guidelines now prohibit ______ on airplanes.</text>
		
	</cardData>
	<cardData>
		<text>War! What is it good for?</text>
		
	</cardData>
	<cardData>
		<text>What are my parents hiding from me?</text>
		
	</cardData>
	<cardData>
		<text>What did I bring back from Mexico?</text>
		
	</cardData>
	<cardData>
		<text>What did the US airdrop to the children of Afghanistan?</text>
		
	</cardData>
	<cardData>
		<text>What did Vin Diesel eat for dinner?</text>
		
	</cardData>
	<cardData>
		<text>What ended my last relationship?</text>
		
	</cardData>
	<cardData>
		<text>What gives me uncontrollable gas?</text>
		
	</cardData>
	<cardData>
		<text>What helps Obama unwind?</text>
		
	</cardData>
	<cardData>
		<text>What is Batman's guilty pleasure?</text>
		
	</cardData>
	<cardData>
		<text>What never fails to liven up the party?</text>
		
	</cardData>
	<cardData>
		<text>What will always get you laid?</text>
		
	</cardData>
	<cardData>
		<text>What would grandma find disturbing, yet oddly charming?</text>
		
	</cardData>
	<cardData>
		<text>What's a girl's best friend?</text>
		
	</cardData>
	<cardData>
		<text>What's my secret power?</text>
		
	</cardData>
	<cardData>
		<text>What's Teach for America using to inspire inner city students to succeed?</text>
		
	</cardData>
	<cardData>
		<text>What's that smell?</text>
		
	</cardData>
	<cardData>
		<text>What's that sound?</text>
		
	</cardData>
	<cardData>
		<text>What's the next Happy Meal® toy?</text>
		
	</cardData>
	<cardData>
		<text>What's there a ton of in heaven?</text>
		
	</cardData>
	<cardData>
		<text>When I am a billionare, I shall erect a 50-foot statue to commemorate ______.</text>
		
	</cardData>
	<cardData>
		<text>When I am President of the United States, I will create the Department of ______.</text>
		
	</cardData>
	<cardData>
		<text>When I was tripping on acid, ______ turned into ______.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>When Pharaoh remained unmoved, Moses called down a Plague of ______.</text>
		
	</cardData>
	<cardData>
		<text>While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ______.</text>
		
	</cardData>
	<cardData>
		<text>White people like ______.</text>
		
	</cardData>
	<cardData>
		<text>Why am I sticky?</text>
		
	</cardData>
	<cardData>
		<text>Why can't I sleep at night?</text>
		
	</cardData>
	<cardData>
		<text>Why do I hurt all over?</text>
		
	</cardData>
	<cardData>
		<text>______. That's how I want to die.</text>
		
	</cardData>
	<cardData>
		<text>BILLY MAYS HERE FOR ______.</text>
		
	</cardData>
	<cardData>
		<text>During his childhood, Salvador Dali produced hundreds of paintings of ______.</text>
		
	</cardData>
	<cardData>
		<text>I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.</text>
		
	</cardData>
	<cardData>
		<text>In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?</text>
		
	</cardData>
	<cardData>
		<text>In Michael Jackson's final moments, he thought about ______.</text>
		
	</cardData>
	<cardData>
		<text>Major League Baseball has banned ______ for giving players an unfair advantage.</text>
		
	</cardData>
	<cardData>
		<text>Rumor has it that Vladimir Putin's favorite dish is ______ stuffed with ______.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>Studies show that lab rats navigate mazes 50% faster after being exposed to ______.</text>
		
	</cardData>
	<cardData>
		<text>The Smithsonian Museum of Natural History has just opened an interactive exhibit on ______.</text>
		
	</cardData>
	<cardData>
		<text>What am I giving up for Lent?</text>
		
	</cardData>
	<cardData>
		<text>What do old people smell like?</text>
		
	</cardData>
	<cardData>
		<text>What does Dick Cheney prefer?</text>
		
	</cardData>
	<cardData>
		<text>What don't you want to find in your Chinese food?</text>
		
	</cardData>
	<cardData>
		<text>What gets better with age?</text>
		
	</cardData>
	<cardData>
		<text>What will I bring back in time to convince people that I am a powerful wizard?</text>
		
	</cardData>
	<cardData>
		<text>What's my anti-drug?</text>
		
	</cardData>
	<cardData>
		<text>What's the most emo?</text>
		
	</cardData>
	<cardData>
		<text>What's the new fad diet?</text>
		
	</cardData>
	<cardData>
		<text>What's the next superhero/sidekick duo?</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>______. That was so metal.</text>
		
	</cardData>
	<cardData>
		<text>A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ______.</text>
		
	</cardData>
	<cardData>
		<text>After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ______.</text>
		
	</cardData>
	<cardData>
		<text>Fun tip! When your man asks you to go down on him, try surprising him with ______ instead.</text>
		
	</cardData>
	<cardData>
		<text>Hey Reddit! I'm ______. Ask me anything.</text>
		
	</cardData>
	<cardData>
		<text>I get by with a little help from ______.</text>
		
	</cardData>
	<cardData>
		<text>I'm going on a cleanse this week. Nothing but kale juice and ______.</text>
		
	</cardData>
	<cardData>
		<text>Introducing the amazing superhero/sidekick duo! It's ______ and ______!</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>Introducing X-Treme Baseball! It's like baseball, but with ______!</text>
		
	</cardData>
	<cardData>
		<text>Just saw this upsetting video! Please retweet!! #stop______</text>
		
	</cardData>
	<cardData>
		<text>Kids, I don't need drugs to get high. I'm high on ______.</text>
		
	</cardData>
	<cardData>
		<text>Now at the Smithsonian: an interactive exhibit on ______.</text>
		
	</cardData>
	<cardData>
		<text>The new Chevy Tahoe. With the power and space to take ______ everywhere you go.</text>
		
	</cardData>
	<cardData>
		<text>They said we were crazy. They said we couldn't put ______ inside of ______. They were wrong.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>Today on Maury: "Help! My son is ______!"</text>
		
	</cardData>
	<cardData>
		<text>Uh, hey guys, I know this was my idea, but I'm having serious doubts about ______.</text>
		
	</cardData>
	<cardData>
		<text>Well if you'll excuse me, gentlemen, I have a date with ______.</text>
		
	</cardData>
	<cardData>
		<text>What don't you want to find in your Kung Pao chicken?</text>
		
	</cardData>
	<cardData>
		<text>What is George W. Bush thinking about right now?</text>
		
	</cardData>
	<cardData>
		<text>What made my first kiss so awkward?</text>
		
	</cardData>
	<cardData>
		<text>________: Once you pop, the fun don't stop!</text>
		
	</cardData>
	<cardData>
		<text>________? Jim'll fix it!</text>
		
	</cardData>
	<cardData>
		<text>________. That's why mums go to Iceland.</text>
		
	</cardData>
	<cardData>
		<text>______? There's an app for that.</text>
		
	</cardData>
	<cardData>
		<text>After Hurricane Katrina, Sean Penn brought ______ to all the people of New Orleans.</text>
		
	</cardData>
	<cardData>
		<text>Airport security guidelines now prohibit ________ on airplanes.</text>
		
	</cardData>
	<cardData>
		<text>And the BAFTA for ________ goes to ________. </text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>Anthropologists have recently discovered a primitive tribe that worships ______.</text>
		
	</cardData>
	<cardData>
		<text>Channel 4 presents ________, the story of ________.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>Channel 5's new reality show features eight washed-up celebrities living with ________.</text>
		
	</cardData>
	<cardData>
		<text>Coming to the West End this year, ________: The Musical.</text>
		
	</cardData>
	<cardData>
		<text>Daddy, why is mummy crying?</text>
		
	</cardData>
	<cardData>
		<text>Dear Agony Aunt, I'm having some trouble with ________ and I need your advice.</text>
		
	</cardData>
	<cardData>
		<text>Due to a PR fiasco, Walmart no longer offers ______.</text>
		
	</cardData>
	<cardData>
		<text>During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ______.</text>
		
	</cardData>
	<cardData>
		<text>I wish I hadn't lost the instruction manual for ______.</text>
		
	</cardData>
	<cardData>
		<text>I'm sorry,Sir, but I couldn't complete my homework because of ________.</text>
		
	</cardData>
	<cardData>
		<text>In 1,000 years, when paper money is but a distant memory, ______ will be our currency.</text>
		
	</cardData>
	<cardData>
		<text>In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ______.</text>
		
	</cardData>
	<cardData>
		<text>In her latest feature-length film, Tracy Beaker struggles with ________ for the first time.</text>
		
	</cardData>
	<cardData>
		<text>In his new summer comedy, Rob Schneider is ______ trapped in the body of ______.</text>
		<pick>2</pick>
	</cardData>
	<cardData>
		<text>In Wormwood Scrubs, word is you can trade 200 cigarettes for ________.</text>
		
	</cardData>
	<cardData>
		<text>Instead of coal, Father Christmas now gives bad children ________.</text>
		
	</cardData>
	<cardData>
		<text>Life was difficult for cavemen before ______.</text>
		
	</cardData>
	<cardData>
		<text>Next on Sky Sports: The World Championship of ________.</text>
		
	</cardData>
	<cardData>
		<text>Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and ________.</text>
		
	</cardData>
	<cardData>
		<text>O Canada, we stand on guard for ______.</text>
		
	</cardData>
	<cardData>
		<text>Sorry everyone, I just ______.</text>
		
	</cardData>
	<cardData>
		<text>The Natural History Museum has just opened an interactive exhibit on ________.</text>
		
	</cardData>
	<cardData>
		<text>The school field trip was completely ruined by ________.</text>
		
	</cardData>
	<cardData>
		<text>The TFL apologizes for the delay in train service due to ________.</text>
		
	</cardData>
	<cardData>
		<text>The theme for next year's Eurovision Song Contest is "We are ________."</text>
		
	</cardData>
	<cardData>
		<text>The U.S. has begun airdropping ______ to the children of Afghanistan.</text>
		
	</cardData>
	<cardData>
		<text>Today on The Jeremy Kyle Show: "Help! My son is ________!"</text>
		
	</cardData>
	<cardData>
		<text>What are school administrators using to curb rampant teenage pregnancy?</text>
		
	</cardData>
	<cardData>
		<text>What did I bring back from Amsterdam?</text>
		
	</cardData>
	<cardData>
		<text>What kept Margaret Thatcher busy in her waning years?</text>
		
	</cardData>
	<cardData>
		<text>What's the crustiest?</text>
		
	</cardData>
	<cardData>
		<text>What's the next superhero?</text>
		
	</cardData>
	<cardData>
		<text>When I am Prime Minister of the United Kingdom, I will create the Ministry of ________.</text>
		
	</cardData>
	<cardData>
		<text>When I'm in prison, I'll have ______ smuggled in.</text>
		
	</cardData>
	<cardData>
		<text>Who stole the cookies from the cookie jar?</text>
		
	</cardData>
</blackdeck>
