<?xml version="1.0"?>
<!DOCTYPE whitedeck [
		<!ELEMENT whitedeck (cardData)*>
		<!ATTLIST whitedeck
				name CDATA #REQUIRED>
		<!ELEMENT cardData (text)*>
		<!ELEMENT text (#PCDATA)>
		]>
<whitedeck name="Main deck">
	<cardData>
		<text>50,000 volts straight to the nipples.</text>
	</cardData>
	<cardData>
		<text>72 virgins.</text>
	</cardData>
	<cardData>
		<text>8 oz. of sweet Mexican black-tar heroin.</text>
	</cardData>
	<cardData>
		<text>A bag of magic beans.</text>
	</cardData>
	<cardData>
		<text>A balanced breakfast.</text>
	</cardData>
	<cardData>
		<text>(I am doing Kegels right now.)</text>
	</cardData>
	<cardData>
		<text>A bitch slap.</text>
	</cardData>
	<cardData>
		<text>A bleached asshole.</text>
	</cardData>
	<cardData>
		<text>A Bop It™.</text>
	</cardData>
	<cardData>
		<text>A brain tumor.</text>
	</cardData>
	<cardData>
		<text>A cooler full of organs.</text>
	</cardData>
	<cardData>
		<text>A defective condom.</text>
	</cardData>
	<cardData>
		<text>A disappointing birthday party.</text>
	</cardData>
	<cardData>
		<text>A falcon with a cap on its head.</text>
	</cardData>
	<cardData>
		<text>A fetus.</text>
	</cardData>
	<cardData>
		<text>2 Girls 1 Cup.</text>
	</cardData>
	<cardData>
		<text>A gassy antelope.</text>
	</cardData>
	<cardData>
		<text>A gentle caress of the inner thigh.</text>
	</cardData>
	<cardData>
		<text>A good sniff.</text>
	</cardData>
	<cardData>
		<text>A homoerotic volleyball montage.</text>
	</cardData>
	<cardData>
		<text>A lifetime of sadness.</text>
	</cardData>
	<cardData>
		<text>A live studio audience.</text>
	</cardData>
	<cardData>
		<text>400 years of colonial atrocities.</text>
	</cardData>
	<cardData>
		<text>A mating display.</text>
	</cardData>
	<cardData>
		<text>A micropenis.</text>
	</cardData>
	<cardData>
		<text>A micropig wearing a tiny raincoat and booties.</text>
	</cardData>
	<cardData>
		<text>A middle-aged man on roller skates.</text>
	</cardData>
	<cardData>
		<text>A mime having a stroke.</text>
	</cardData>
	<cardData>
		<text>A monkey smoking a cigar.</text>
	</cardData>
	<cardData>
		<text>A mopey zoo lion.</text>
	</cardData>
	<cardData>
		<text>A murder most foul.</text>
	</cardData>
	<cardData>
		<text>A pyramid of severed heads.</text>
	</cardData>
	<cardData>
		<text>A really cool hat.</text>
	</cardData>
	<cardData>
		<text>A robust mongoloid.</text>
	</cardData>
	<cardData>
		<text>A sad handjob.</text>
	</cardData>
	<cardData>
		<text>A salty surprise.</text>
	</cardData>
	<cardData>
		<text>A sassy black woman.</text>
	</cardData>
	<cardData>
		<text>A ball of earwax, semen, and toenail clippings.</text>
	</cardData>
	<cardData>
		<text>A sea of troubles.</text>
	</cardData>
	<cardData>
		<text>A snapping turtle biting the tip of your penis.</text>
	</cardData>
	<cardData>
		<text>A stray pube.</text>
	</cardData>
	<cardData>
		<text>A subscription to Men's Fitness.</text>
	</cardData>
	<cardData>
		<text>A Super Soaker™ full of cat pee.</text>
	</cardData>
	<cardData>
		<text>A thermonuclear detonation.</text>
	</cardData>
	<cardData>
		<text>A time travel paradox.</text>
	</cardData>
	<cardData>
		<text>A tiny horse.</text>
	</cardData>
	<cardData>
		<text>A tribe of warrior women.</text>
	</cardData>
	<cardData>
		<text>A windmill full of corpses.</text>
	</cardData>
	<cardData>
		<text>A zesty breakfast burrito.</text>
	</cardData>
	<cardData>
		<text>Active listening.</text>
	</cardData>
	<cardData>
		<text>Asians who aren't good at math.</text>
	</cardData>
	<cardData>
		<text>African children.</text>
	</cardData>
	<cardData>
		<text>Agriculture.</text>
	</cardData>
	<cardData>
		<text>AIDS.</text>
	</cardData>
	<cardData>
		<text>Alcoholism.</text>
	</cardData>
	<cardData>
		<text>Altar boys.</text>
	</cardData>
	<cardData>
		<text>Amputees.</text>
	</cardData>
	<cardData>
		<text>An asymmetric boob job.</text>
	</cardData>
	<cardData>
		<text>A big hoopla about nothing.</text>
	</cardData>
	<cardData>
		<text>An erection that lasts longer than four hours.</text>
	</cardData>
	<cardData>
		<text>An icepick labotomy.</text>
	</cardData>
	<cardData>
		<text>An M. Night Shyamalan plot twist.</text>
	</cardData>
	<cardData>
		<text>An Oedipus complex.</text>
	</cardData>
	<cardData>
		<text>An oversized lollipop.</text>
	</cardData>
	<cardData>
		<text>An ugly face.</text>
	</cardData>
	<cardData>
		<text>Anal beads.</text>
	</cardData>
	<cardData>
		<text>Arnold Schwarzenegger.</text>
	</cardData>
	<cardData>
		<text>Assless chaps.</text>
	</cardData>
	<cardData>
		<text>Authentic Mexican cuisine.</text>
	</cardData>
	<cardData>
		<text>Auschwitz.</text>
	</cardData>
	<cardData>
		<text>AXE Body Spray.</text>
	</cardData>
	<cardData>
		<text>Autocannibalism.</text>
	</cardData>
	<cardData>
		<text>Bill Nye the Science Guy.</text>
	</cardData>
	<cardData>
		<text>Balls.</text>
	</cardData>
	<cardData>
		<text>Barack Obama.</text>
	</cardData>
	<cardData>
		<text>BATMAN!!!</text>
	</cardData>
	<cardData>
		<text>Battlefield amputations.</text>
	</cardData>
	<cardData>
		<text>Becoming a blueberry.</text>
	</cardData>
	<cardData>
		<text>Bees?</text>
	</cardData>
	<cardData>
		<text>Being a dick to children.</text>
	</cardData>
	<cardData>
		<text>Being a motherfucking sorcerer.</text>
	</cardData>
	<cardData>
		<text>Being fabulous.</text>
	</cardData>
	<cardData>
		<text>Being fat and stupid.</text>
	</cardData>
	<cardData>
		<text>Being marginalized.</text>
	</cardData>
	<cardData>
		<text>Being on fire.</text>
	</cardData>
	<cardData>
		<text>Being rich.</text>
	</cardData>
	<cardData>
		<text>Bingeing and purging.</text>
	</cardData>
	<cardData>
		<text>Boogers.</text>
	</cardData>
	<cardData>
		<text>A bit of slap and tickle.</text>
	</cardData>
	<cardData>
		<text>Bitches.</text>
	</cardData>
	<cardData>
		<text>Black people.</text>
	</cardData>
	<cardData>
		<text>Concealing a boner.</text>
	</cardData>
	<cardData>
		<text>Breaking out into song and dance.</text>
	</cardData>
	<cardData>
		<text>Brown people.</text>
	</cardData>
	<cardData>
		<text>Cards Against Humanity.</text>
	</cardData>
	<cardData>
		<text>Catapults.</text>
	</cardData>
	<cardData>
		<text>Centaurs.</text>
	</cardData>
	<cardData>
		<text>Chainsaws for hands.</text>
	</cardData>
	<cardData>
		<text>Child abuse.</text>
	</cardData>
	<cardData>
		<text>Child beauty pageants.</text>
	</cardData>
	<cardData>
		<text>Children on leashes.</text>
	</cardData>
	<cardData>
		<text>Christopher Walken.</text>
	</cardData>
	<cardData>
		<text>A bleached arsehole.</text>
	</cardData>
	<cardData>
		<text>Civilian casualties.</text>
	</cardData>
	<cardData>
		<text>Classist undertones.</text>
	</cardData>
	<cardData>
		<text>Coat hanger abortions.</text>
	</cardData>
	<cardData>
		<text>Count Chocula.</text>
	</cardData>
	<cardData>
		<text>Consensual sex.</text>
	</cardData>
	<cardData>
		<text>Dick Cheney</text>
	</cardData>
	<cardData>
		<text>A brain tumour.</text>
	</cardData>
	<cardData>
		<text>Crippling debt.</text>
	</cardData>
	<cardData>
		<text>Crucifixion.</text>
	</cardData>
	<cardData>
		<text>Doin' it in the butt.</text>
	</cardData>
	<cardData>
		<text>Crystal meth.</text>
	</cardData>
	<cardData>
		<text>Cuddling.</text>
	</cardData>
	<cardData>
		<text>Cybernetic enhancements.</text>
	</cardData>
	<cardData>
		<text>Daddy issues.</text>
	</cardData>
	<cardData>
		<text>Domino's™ Oreo™ Dessert Pizza.</text>
	</cardData>
	<cardData>
		<text>A caress of the inner thigh</text>
	</cardData>
	<cardData>
		<text>Darth Vader.</text>
	</cardData>
	<cardData>
		<text>A cartoon camel enjoying the smooth, refreshing taste of a cigarette.</text>
	</cardData>
	<cardData>
		<text>Dead babies.</text>
	</cardData>
	<cardData>
		<text>Dead parents.</text>
	</cardData>
	<cardData>
		<text>Destroying the evidence.</text>
	</cardData>
	<cardData>
		<text>Eating the last known bison.</text>
	</cardData>
	<cardData>
		<text>Dick fingers.</text>
	</cardData>
	<cardData>
		<text>Edible underpants.</text>
	</cardData>
	<cardData>
		<text>Doing the right thing.</text>
	</cardData>
	<cardData>
		<text>Extremely tight pants.</text>
	</cardData>
	<cardData>
		<text>Drinking alone.</text>
	</cardData>
	<cardData>
		<text>Dropping a chandelier on your enemies and riding the rope up.</text>
	</cardData>
	<cardData>
		<text>Dry heaving.</text>
	</cardData>
	<cardData>
		<text>Dying.</text>
	</cardData>
	<cardData>
		<text>Fancy Feast®.</text>
	</cardData>
	<cardData>
		<text>Fiery poops.</text>
	</cardData>
	<cardData>
		<text>Elderly Japanese men.</text>
	</cardData>
	<cardData>
		<text>Embryonic stem cells.</text>
	</cardData>
	<cardData>
		<text>A Chelsea smile. </text>
	</cardData>
	<cardData>
		<text>Emotions.</text>
	</cardData>
	<cardData>
		<text>Erectile dysfunction.</text>
	</cardData>
	<cardData>
		<text>A clandestine butt scratch.</text>
	</cardData>
	<cardData>
		<text>Estrogen.</text>
	</cardData>
	<cardData>
		<text>Ethnic cleansing.</text>
	</cardData>
	<cardData>
		<text>Eugenics.</text>
	</cardData>
	<cardData>
		<text>Exactly what you'd expect.</text>
	</cardData>
	<cardData>
		<text>Expecting a burp and vomiting on the floor.</text>
	</cardData>
	<cardData>
		<text>Explosions.</text>
	</cardData>
	<cardData>
		<text>Five-Dollar Footlongs™.</text>
	</cardData>
	<cardData>
		<text>Famine.</text>
	</cardData>
	<cardData>
		<text>Former President George W. Bush.</text>
	</cardData>
	<cardData>
		<text>Farting and walking away.</text>
	</cardData>
	<cardData>
		<text>Fear itself.</text>
	</cardData>
	<cardData>
		<text>Getting naked and watching Nickelodeon.</text>
	</cardData>
	<cardData>
		<text>Finger painting.</text>
	</cardData>
	<cardData>
		<text>Fingering.</text>
	</cardData>
	<cardData>
		<text>Firing a rifle into the air while balls deep in a squealing hog.</text>
	</cardData>
	<cardData>
		<text>Half-assed foreplay.</text>
	</cardData>
	<cardData>
		<text>Flesh-eating bacteria.</text>
	</cardData>
	<cardData>
		<text>Flightless birds.</text>
	</cardData>
	<cardData>
		<text>Flying sex snakes.</text>
	</cardData>
	<cardData>
		<text>Foreskin.</text>
	</cardData>
	<cardData>
		<text>Heteronormativity.</text>
	</cardData>
	<cardData>
		<text>Free samples.</text>
	</cardData>
	<cardData>
		<text>Friction.</text>
	</cardData>
	<cardData>
		<text>Friendly fire.</text>
	</cardData>
	<cardData>
		<text>Frolicking.</text>
	</cardData>
	<cardData>
		<text>Full frontal nudity.</text>
	</cardData>
	<cardData>
		<text>Funky fresh rhymes.</text>
	</cardData>
	<cardData>
		<text>Gandhi.</text>
	</cardData>
	<cardData>
		<text>Geese.</text>
	</cardData>
	<cardData>
		<text>A drive-by shooting.</text>
	</cardData>
	<cardData>
		<text>German dungeon porn.</text>
	</cardData>
	<cardData>
		<text>Jerking off into a pool of children's tears.</text>
	</cardData>
	<cardData>
		<text>Getting really high.</text>
	</cardData>
	<cardData>
		<text>Getting so angry that you pop a boner.</text>
	</cardData>
	<cardData>
		<text>Ghosts.</text>
	</cardData>
	<cardData>
		<text>A fanny fart. </text>
	</cardData>
	<cardData>
		<text>Gloryholes.</text>
	</cardData>
	<cardData>
		<text>Goblins.</text>
	</cardData>
	<cardData>
		<text>God.</text>
	</cardData>
	<cardData>
		<text>Grandma.</text>
	</cardData>
	<cardData>
		<text>Grave robbing.</text>
	</cardData>
	<cardData>
		<text>Growing a pair.</text>
	</cardData>
	<cardData>
		<text>Jewish fraternities.</text>
	</cardData>
	<cardData>
		<text>Harry Potter erotica.</text>
	</cardData>
	<cardData>
		<text>A Fleshlight.</text>
	</cardData>
	<cardData>
		<text>Heartwarming orphans.</text>
	</cardData>
	<cardData>
		<text>Her Majesty, Queen Elizabeth II.</text>
	</cardData>
	<cardData>
		<text>Judge Judy.</text>
	</cardData>
	<cardData>
		<text>A foetus. </text>
	</cardData>
	<cardData>
		<text>Homeless people.</text>
	</cardData>
	<cardData>
		<text>Hope.</text>
	</cardData>
	<cardData>
		<text>Hormone injections.</text>
	</cardData>
	<cardData>
		<text>Horrifying laser hair removal accidents.</text>
	</cardData>
	<cardData>
		<text>Horse meat.</text>
	</cardData>
	<cardData>
		<text>Hospice care.</text>
	</cardData>
	<cardData>
		<text>Hot cheese.</text>
	</cardData>
	<cardData>
		<text>Hot people.</text>
	</cardData>
	<cardData>
		<text>Inappropriate yodeling.</text>
	</cardData>
	<cardData>
		<text>Incest.</text>
	</cardData>
	<cardData>
		<text>A ginger's freckled ballsack.</text>
	</cardData>
	<cardData>
		<text>A grande sugar-free iced soy caramel macchiato.</text>
	</cardData>
	<cardData>
		<text>Italians.</text>
	</cardData>
	<cardData>
		<text>Kanye West.</text>
	</cardData>
	<cardData>
		<text>Kids with ass cancer.</text>
	</cardData>
	<cardData>
		<text>A Gypsy curse.</text>
	</cardData>
	<cardData>
		<text>Lunchables™.</text>
	</cardData>
	<cardData>
		<text>Justin Bieber.</text>
	</cardData>
	<cardData>
		<text>Kamikaze pilots.</text>
	</cardData>
	<cardData>
		<text>Michelle Obama's arms.</text>
	</cardData>
	<cardData>
		<text>Keanu Reeves.</text>
	</cardData>
	<cardData>
		<text>Mr. Clean, right behind you.</text>
	</cardData>
	<cardData>
		<text>Lactation.</text>
	</cardData>
	<cardData>
		<text>Lady Gaga.</text>
	</cardData>
	<cardData>
		<text>Lance Armstrong's missing testicle.</text>
	</cardData>
	<cardData>
		<text>Land mines.</text>
	</cardData>
	<cardData>
		<text>Laying an egg.</text>
	</cardData>
	<cardData>
		<text>Leprosy.</text>
	</cardData>
	<cardData>
		<text>Licking things to claim them as your own.</text>
	</cardData>
	<cardData>
		<text>Lockjaw.</text>
	</cardData>
	<cardData>
		<text>Lumberjack fantasies.</text>
	</cardData>
	<cardData>
		<text>Not wearing pants.</text>
	</cardData>
	<cardData>
		<text>A LAN party.</text>
	</cardData>
	<cardData>
		<text>Making a pouty face.</text>
	</cardData>
	<cardData>
		<text>Man meat.</text>
	</cardData>
	<cardData>
		<text>Masturbation.</text>
	</cardData>
	<cardData>
		<text>Me time.</text>
	</cardData>
	<cardData>
		<text>MechaHitler.</text>
	</cardData>
	<cardData>
		<text>Men.</text>
	</cardData>
	<cardData>
		<text>Menstrual rage.</text>
	</cardData>
	<cardData>
		<text>Michael Jackson.</text>
	</cardData>
	<cardData>
		<text>Pedophiles.</text>
	</cardData>
	<cardData>
		<text>A look-see.</text>
	</cardData>
	<cardData>
		<text>Morgan Freeman's voice.</text>
	</cardData>
	<cardData>
		<text>Mouth herpes.</text>
	</cardData>
	<cardData>
		<text>Poopy diapers.</text>
	</cardData>
	<cardData>
		<text>Multiple stab wounds.</text>
	</cardData>
	<cardData>
		<text>Mutually assured destruction.</text>
	</cardData>
	<cardData>
		<text>Queefing.</text>
	</cardData>
	<cardData>
		<text>My collection of high-tech sex toys.</text>
	</cardData>
	<cardData>
		<text>A mad cow.</text>
	</cardData>
	<cardData>
		<text>My genitals.</text>
	</cardData>
	<cardData>
		<text>My humps.</text>
	</cardData>
	<cardData>
		<text>My inner demons.</text>
	</cardData>
	<cardData>
		<text>My relationship status.</text>
	</cardData>
	<cardData>
		<text>My sex life.</text>
	</cardData>
	<cardData>
		<text>My soul.</text>
	</cardData>
	<cardData>
		<text>My vagina.</text>
	</cardData>
	<cardData>
		<text>Natural male enhancement.</text>
	</cardData>
	<cardData>
		<text>Natural selection.</text>
	</cardData>
	<cardData>
		<text>Nazis.</text>
	</cardData>
	<cardData>
		<text>Necrophilia.</text>
	</cardData>
	<cardData>
		<text>Nickelback.</text>
	</cardData>
	<cardData>
		<text>Nicolas Cage.</text>
	</cardData>
	<cardData>
		<text>Nipple blades.</text>
	</cardData>
	<cardData>
		<text>Not giving a shit about the Third World.</text>
	</cardData>
	<cardData>
		<text>Not reciprocating oral sex.</text>
	</cardData>
	<cardData>
		<text>Republicans.</text>
	</cardData>
	<cardData>
		<text>Object permanence.</text>
	</cardData>
	<cardData>
		<text>Old-people smell.</text>
	</cardData>
	<cardData>
		<text>One trillion dollars.</text>
	</cardData>
	<cardData>
		<text>Oompa-Loompas.</text>
	</cardData>
	<cardData>
		<text>Opposable thumbs.</text>
	</cardData>
	<cardData>
		<text>Overcompensation.</text>
	</cardData>
	<cardData>
		<text>Pac-Man uncontrollably guzzling cum.</text>
	</cardData>
	<cardData>
		<text>Panda sex.</text>
	</cardData>
	<cardData>
		<text>Passive-aggressive Post-it notes.</text>
	</cardData>
	<cardData>
		<text>Road head.</text>
	</cardData>
	<cardData>
		<text>Peeing a little bit.</text>
	</cardData>
	<cardData>
		<text>A madman who lives in a police box and kidnaps women.</text>
	</cardData>
	<cardData>
		<text>Penis envy.</text>
	</cardData>
	<cardData>
		<text>Pictures of boobs.</text>
	</cardData>
	<cardData>
		<text>Pixelated bukkake.</text>
	</cardData>
	<cardData>
		<text>Police Brutality.</text>
	</cardData>
	<cardData>
		<text>Pooping back and forth.Forever.</text>
	</cardData>
	<cardData>
		<text>Robert Downey Jr.</text>
	</cardData>
	<cardData>
		<text>Poor life choices.</text>
	</cardData>
	<cardData>
		<text>Poor people.</text>
	</cardData>
	<cardData>
		<text>Poorly-timed Holocaust jokes.</text>
	</cardData>
	<cardData>
		<text>Powerful thighs.</text>
	</cardData>
	<cardData>
		<text>Praying the gay away.</text>
	</cardData>
	<cardData>
		<text>Preteens.</text>
	</cardData>
	<cardData>
		<text>Pretending to care.</text>
	</cardData>
	<cardData>
		<text>Puberty.</text>
	</cardData>
	<cardData>
		<text>Pulling out.</text>
	</cardData>
	<cardData>
		<text>Puppies!</text>
	</cardData>
	<cardData>
		<text>Shaquille O'Neal's acting career.</text>
	</cardData>
	<cardData>
		<text>Racism.</text>
	</cardData>
	<cardData>
		<text>Raptor attacks.</text>
	</cardData>
	<cardData>
		<text>Repression.</text>
	</cardData>
	<cardData>
		<text>Skeletor.</text>
	</cardData>
	<cardData>
		<text>Smallpox blankets.</text>
	</cardData>
	<cardData>
		<text>Switching to Geico®.</text>
	</cardData>
	<cardData>
		<text>RoboCop.</text>
	</cardData>
	<cardData>
		<text>A man on the brink of orgasm.</text>
	</cardData>
	<cardData>
		<text>A moment of silence.</text>
	</cardData>
	<cardData>
		<text>Science.</text>
	</cardData>
	<cardData>
		<text>Scientology.</text>
	</cardData>
	<cardData>
		<text>Sean Connery.</text>
	</cardData>
	<cardData>
		<text>Sean Penn.</text>
	</cardData>
	<cardData>
		<text>The Amish.</text>
	</cardData>
	<cardData>
		<text>Self-loathing.</text>
	</cardData>
	<cardData>
		<text>Seppuku.</text>
	</cardData>
	<cardData>
		<text>Serfdom.</text>
	</cardData>
	<cardData>
		<text>A much younger woman.</text>
	</cardData>
	<cardData>
		<text>A neglected Tamagotchi™.</text>
	</cardData>
	<cardData>
		<text>Sexual tension.</text>
	</cardData>
	<cardData>
		<text>Sexy pillow fights.</text>
	</cardData>
	<cardData>
		<text>Shapeshifters.</text>
	</cardData>
	<cardData>
		<text>The Boy Scouts of America.</text>
	</cardData>
	<cardData>
		<text>Shiny objects.</text>
	</cardData>
	<cardData>
		<text>Silence.</text>
	</cardData>
	<cardData>
		<text>The Care Bear Stare.</text>
	</cardData>
	<cardData>
		<text>The entire Mormon Tabernacle Choir.</text>
	</cardData>
	<cardData>
		<text>Smegma.</text>
	</cardData>
	<cardData>
		<text>Sniffing glue.</text>
	</cardData>
	<cardData>
		<text>The Hamburglar.</text>
	</cardData>
	<cardData>
		<text>Soup that is too hot.</text>
	</cardData>
	<cardData>
		<text>Spectacular abs.</text>
	</cardData>
	<cardData>
		<text>Sperm whales.</text>
	</cardData>
	<cardData>
		<text>Spontaneous human combustion.</text>
	</cardData>
	<cardData>
		<text>Stalin.</text>
	</cardData>
	<cardData>
		<text>Stephen Hawking talking dirty.</text>
	</cardData>
	<cardData>
		<text>A nice cup of tea.</text>
	</cardData>
	<cardData>
		<text>Sunshine and rainbows.</text>
	</cardData>
	<cardData>
		<text>Surprise sex!</text>
	</cardData>
	<cardData>
		<text>Sweet, sweet vengeance.</text>
	</cardData>
	<cardData>
		<text>The hardworking Mexican.</text>
	</cardData>
	<cardData>
		<text>Swooping.</text>
	</cardData>
	<cardData>
		<text>Synergistic management solutions.</text>
	</cardData>
	<cardData>
		<text>Taking off your shirt.</text>
	</cardData>
	<cardData>
		<text>Tasteful sideboob.</text>
	</cardData>
	<cardData>
		<text>Teaching a robot to love.</text>
	</cardData>
	<cardData>
		<text>Teenage pregnancy.</text>
	</cardData>
	<cardData>
		<text>Tentacle porn.</text>
	</cardData>
	<cardData>
		<text>Testicular torsion.</text>
	</cardData>
	<cardData>
		<text>The Hustle.</text>
	</cardData>
	<cardData>
		<text>The Big Bang.</text>
	</cardData>
	<cardData>
		<text>The Blood of Christ.</text>
	</cardData>
	<cardData>
		<text>The invisible hand.</text>
	</cardData>
	<cardData>
		<text>The Kool-Aid Man.</text>
	</cardData>
	<cardData>
		<text>The Chinese gymnastics team.</text>
	</cardData>
	<cardData>
		<text>The clitoris.</text>
	</cardData>
	<cardData>
		<text>A pangender octopus who roams the cosmos in search of love.</text>
	</cardData>
	<cardData>
		<text>The Devil Himself.</text>
	</cardData>
	<cardData>
		<text>The Little Engine That Could.</text>
	</cardData>
	<cardData>
		<text>The female orgasm.</text>
	</cardData>
	<cardData>
		<text>The Force.</text>
	</cardData>
	<cardData>
		<text>The gays.</text>
	</cardData>
	<cardData>
		<text>The glass ceiling.</text>
	</cardData>
	<cardData>
		<text>The Great Depression.</text>
	</cardData>
	<cardData>
		<text>The Make-A-Wish® Foundation.</text>
	</cardData>
	<cardData>
		<text>The penny whistle solo from "My Heart Will Go On".</text>
	</cardData>
	<cardData>
		<text>The heart of a child.</text>
	</cardData>
	<cardData>
		<text>The Holy Bible.</text>
	</cardData>
	<cardData>
		<text>The homosexual agenda.</text>
	</cardData>
	<cardData>
		<text>The Rapture.</text>
	</cardData>
	<cardData>
		<text>The inevitable heat death of the universe.</text>
	</cardData>
	<cardData>
		<text>The South.</text>
	</cardData>
	<cardData>
		<text>The Jews.</text>
	</cardData>
	<cardData>
		<text>The KKK</text>
	</cardData>
	<cardData>
		<text>The Underground Railroad.</text>
	</cardData>
	<cardData>
		<text>Third base.</text>
	</cardData>
	<cardData>
		<text>Toni Morrison's vagina.</text>
	</cardData>
	<cardData>
		<text>The milkman.</text>
	</cardData>
	<cardData>
		<text>The miracle of childbirth.</text>
	</cardData>
	<cardData>
		<text>A posh wank.</text>
	</cardData>
	<cardData>
		<text>Used panties.</text>
	</cardData>
	<cardData>
		<text>Vehicular manslaughter.</text>
	</cardData>
	<cardData>
		<text>A saxophone solo.</text>
	</cardData>
	<cardData>
		<text>The placenta.</text>
	</cardData>
	<cardData>
		<text>The Pope.</text>
	</cardData>
	<cardData>
		<text>The profoundly handicapped.</text>
	</cardData>
	<cardData>
		<text>Waking up half-naked in a Denny's parking lot.</text>
	</cardData>
	<cardData>
		<text>The Rev. Dr. Martin Luther King, Jr.</text>
	</cardData>
	<cardData>
		<text>A sickly child-king.</text>
	</cardData>
	<cardData>
		<text>Wiping her butt.</text>
	</cardData>
	<cardData>
		<text>The terrorists.</text>
	</cardData>
	<cardData>
		<text>The true meaning of Christmas.</text>
	</cardData>
	<cardData>
		<text>Women in yogurt commercials.</text>
	</cardData>
	<cardData>
		<text>A sober Irishman who doesn't care for potatoes.</text>
	</cardData>
	<cardData>
		<text>The violation of our most basic human rights.</text>
	</cardData>
	<cardData>
		<text>A can of whoop-ass.</text>
	</cardData>
	<cardData>
		<text>The World of Warcraft.</text>
	</cardData>
	<cardData>
		<text>A spastic nerd.</text>
	</cardData>
	<cardData>
		<text>All-you-can-eat shrimp for $4.99.</text>
	</cardData>
	<cardData>
		<text>A thousand Scottish warriors lifting their kilts in unison.</text>
	</cardData>
	<cardData>
		<text>Throwing a virgin into a volcano.</text>
	</cardData>
	<cardData>
		<text>Tom Cruise.</text>
	</cardData>
	<cardData>
		<text>An M16 assault rifle.</text>
	</cardData>
	<cardData>
		<text>Two midgets shitting into a bucket.</text>
	</cardData>
	<cardData>
		<text>Unfathomable stupidity.</text>
	</cardData>
	<cardData>
		<text>Cheating in the Special Olympics.</text>
	</cardData>
	<cardData>
		<text>Helplessly giggling at the mention of Hutus and Tutsis.</text>
	</cardData>
	<cardData>
		<text>Viagra®.</text>
	</cardData>
	<cardData>
		<text>Vigorous jazz hands.</text>
	</cardData>
	<cardData>
		<text>Vikings.</text>
	</cardData>
	<cardData>
		<text>Waiting till marriage.</text>
	</cardData>
	<cardData>
		<text>Home video of Oprah sobbing into a Lean Cuisine®.</text>
	</cardData>
	<cardData>
		<text>Wet dreams.</text>
	</cardData>
	<cardData>
		<text>Whipping it out.</text>
	</cardData>
	<cardData>
		<text>White people.</text>
	</cardData>
	<cardData>
		<text>White privilege.</text>
	</cardData>
	<cardData>
		<text>Hurricane Katrina.</text>
	</cardData>
	<cardData>
		<text>Wifely duties.</text>
	</cardData>
	<cardData>
		<text>William Shatner.</text>
	</cardData>
	<cardData>
		<text>Winking at old people.</text>
	</cardData>
	<cardData>
		<text>The chronic.</text>
	</cardData>
	<cardData>
		<text>The Tempur-Pedic® Swedish Sleep System™.</text>
	</cardData>
	<cardData>
		<text>Women's suffrage.</text>
	</cardData>
	<cardData>
		<text>World peace.</text>
	</cardData>
	<cardData>
		<text>Yeast.</text>
	</cardData>
	<cardData>
		<text>A Tim Hortons franchise.</text>
	</cardData>
	<cardData>
		<text>A bucket of fish heads.</text>
	</cardData>
	<cardData>
		<text>Advice from a wise, old black man.</text>
	</cardData>
	<cardData>
		<text>A vajazzled vagina.</text>
	</cardData>
	<cardData>
		<text>A vindaloo poo. </text>
	</cardData>
	<cardData>
		<text>A wheelchair death race.</text>
	</cardData>
	<cardData>
		<text>A white van man.</text>
	</cardData>
	<cardData>
		<text>Some god damn peace and quiet.</text>
	</cardData>
	<cardData>
		<text>Abstinence.</text>
	</cardData>
	<cardData>
		<text>Accidentally slipping yourself a roofie.</text>
	</cardData>
	<cardData>
		<text>Adult Friendfinder.</text>
	</cardData>
	<cardData>
		<text>All-you-can-eat shrimp for $8.99.</text>
	</cardData>
	<cardData>
		<text>Dying of dysentery.</text>
	</cardData>
	<cardData>
		<text>Genghis Khan.</text>
	</cardData>
	<cardData>
		<text>America.</text>
	</cardData>
	<cardData>
		<text>American Gladiators.</text>
	</cardData>
	<cardData>
		<text>An AK-47 assault rifle.</text>
	</cardData>
	<cardData>
		<text>An AR-15 assault rifle.</text>
	</cardData>
	<cardData>
		<text>An argument with Richard Dawkins.</text>
	</cardData>
	<cardData>
		<text>An endless stream of diarrhea.</text>
	</cardData>
	<cardData>
		<text>An entrenched class system.</text>
	</cardData>
	<cardData>
		<text>Muhammad (Praise Be Unto Him).</text>
	</cardData>
	<cardData>
		<text>An honest cop with nothing left to lose.</text>
	</cardData>
	<cardData>
		<text>Natalie Portman.</text>
	</cardData>
	<cardData>
		<text>An icy handjob from an Edmonton hooker.</text>
	</cardData>
	<cardData>
		<text>Anything that comes out of Prince Philip's mouth.</text>
	</cardData>
	<cardData>
		<text>Prancing.</text>
	</cardData>
	<cardData>
		<text>Public ridicule.</text>
	</cardData>
	<cardData>
		<text>Badger culling.</text>
	</cardData>
	<cardData>
		<text>Same-sex ice dancing.</text>
	</cardData>
	<cardData>
		<text>Bananas in Pajamas.</text>
	</cardData>
	<cardData>
		<text>Being Canadian.</text>
	</cardData>
	<cardData>
		<text>Being hunted like a fox.</text>
	</cardData>
	<cardData>
		<text>Bestiality.</text>
	</cardData>
	<cardData>
		<text>Take-backsies.</text>
	</cardData>
	<cardData>
		<text>Bio-engineered assault turtles with acid breath.</text>
	</cardData>
	<cardData>
		<text>The art of seduction.</text>
	</cardData>
	<cardData>
		<text>Blood, toil, tears, and sweat.</text>
	</cardData>
	<cardData>
		<text>Blowing up Parliament.</text>
	</cardData>
	<cardData>
		<text>The folly of man.</text>
	</cardData>
	<cardData>
		<text>The light of a billion suns.</text>
	</cardData>
	<cardData>
		<text>Bogies.</text>
	</cardData>
	<cardData>
		<text>Bond, James Bond.</text>
	</cardData>
	<cardData>
		<text>Bono.</text>
	</cardData>
	<cardData>
		<text>The token minority.</text>
	</cardData>
	<cardData>
		<text>Vigilante justice.</text>
	</cardData>
	<cardData>
		<text>When you fart and a little bit comes out.</text>
	</cardData>
	<cardData>
		<text>YOU MUST CONSTRUCT ADDITIONAL PYLONS.</text>
	</cardData>
	<cardData>
		<text>Aaron Burr.</text>
	</cardData>
	<cardData>
		<text>Adderall™.</text>
	</cardData>
	<cardData>
		<text>Figgy pudding.</text>
	</cardData>
	<cardData>
		<text>Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.</text>
	</cardData>
	<cardData>
		<text>GoGurt®.</text>
	</cardData>
	<cardData>
		<text>Hot Pockets®.</text>
	</cardData>
	<cardData>
		<text>Racially-biased SAT questions.</text>
	</cardData>
	<cardData>
		<text>Ronald Reagan.</text>
	</cardData>
	<cardData>
		<text>Rush Limbaugh's soft, shitty body.</text>
	</cardData>
	<cardData>
		<text>The Three-Fifths compromise.</text>
	</cardData>
	<cardData>
		<text>The Trail of Tears</text>
	</cardData>
	<cardData>
		<text>Historically black colleges.</text>
	</cardData>
	<cardData>
		<text>John Wilkes Booth</text>
	</cardData>
	<cardData>
		<text>Booby-trapping the house to foil burglars.</text>
	</cardData>
	<cardData>
		<text>Buckfast Tonic Wine.</text>
	</cardData>
	<cardData>
		<text>Burning down the White House.</text>
	</cardData>
	<cardData>
		<text>Canada: America's Hat.</text>
	</cardData>
	<cardData>
		<text>Canned tuna with extra dolphin.</text>
	</cardData>
	<cardData>
		<text>Giving 110%</text>
	</cardData>
	<cardData>
		<text>A death ray.</text>
	</cardData>
	<cardData>
		<text>A hot mess.</text>
	</cardData>
	<cardData>
		<text>Charisma.</text>
	</cardData>
	<cardData>
		<text>A sausage festival.</text>
	</cardData>
	<cardData>
		<text>Cheating in the Paralympics.</text>
	</cardData>
	<cardData>
		<text>A wisecracking terrorist.</text>
	</cardData>
	<cardData>
		<text>Actually taking candy from a baby.</text>
	</cardData>
	<cardData>
		<text>Chivalry.</text>
	</cardData>
	<cardData>
		<text>New Age music.</text>
	</cardData>
	<cardData>
		<text>An uppercut.</text>
	</cardData>